console.log("a: ");
console.log(+ "15" + 5);
console.log("b: ");
console.log("88" + 1);
console.log("c: ");
console.log(typeof ("88" + 1));
console.log("d: ");
console.log(- "5" + 15);
console.log("e: ");
console.log(- 5 - "15");
console.log("f: ");
var x= 1;
var y = 88;
var z = 0;
z = ++y + z;
console.log(z);
